// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeHYrajjPgcaSZDyjmlGDrAikbl-gzaMs',
    appId: '1:704018466082:web:e4a6c19c110d9cf342d17b',
    messagingSenderId: '704018466082',
    projectId: 'adoptini-a15ed',
    authDomain: 'adoptini-a15ed.firebaseapp.com',
    storageBucket: 'adoptini-a15ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMoTS4eZE5MY7F0_20HQ8Y6gwpWjhQ_g',
    appId: '1:704018466082:android:4a85f323f9bf7eb342d17b',
    messagingSenderId: '704018466082',
    projectId: 'adoptini-a15ed',
    storageBucket: 'adoptini-a15ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgnndPvW_kFLPhmyGN0nyJER6JHpp5CZE',
    appId: '1:704018466082:ios:c48957eac0129bec42d17b',
    messagingSenderId: '704018466082',
    projectId: 'adoptini-a15ed',
    storageBucket: 'adoptini-a15ed.appspot.com',
    iosBundleId: 'com.zch.adoptini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgnndPvW_kFLPhmyGN0nyJER6JHpp5CZE',
    appId: '1:704018466082:ios:18c479db2fdcd55642d17b',
    messagingSenderId: '704018466082',
    projectId: 'adoptini-a15ed',
    storageBucket: 'adoptini-a15ed.appspot.com',
    iosBundleId: 'com.zch.adoptini.RunnerTests',
  );
}
